### ISSUE TITLE
Update to the latest Qt 5.15-based stable version of the Platform and SDK

### ISSUE THREAD

**Issue by rgoubet** [flathub/net.puddletag.puddletag#10]
When running `flatpak update`:

```
Info: runtime org.kde.Platform branch 5.15-22.08 is end-of-life, with reason:
   We strongly recommend moving to the latest Qt 5.15-based stable version of the Platform and SDK
```

**Comment by eylenburg** [comment]
When I tried upgrading to the latest Qt 5.15-based platform, it didn't work because of some upstream bug which is still open: 
https://github.com/flathub/net.puddletag.puddletag/pull/5
https://github.com/pyparsing/pyparsing/issues/548
